- name: keeping all variables at one place and refering it 
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: vaibles files
    ansible.builtin.debug:
      msg: "I am  {{NAME}} {{AGE}} ,{{VILLAGE}}"
  - name: variables
    vars:
    ansible.builtin.debug:
      msg: "Task level variables"  
              



