- name: keeping all variables at one place and refering it 
  hosts: localhost
  vars_files:
  - variables.yml
  tasks:
  - name: vaibles files
    ansible.builtin.debug:
      msg: "I am  {{NAME}} {{AGE}} ,{{VILLAGE}}"



