- name: practice promt variables
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt:   please enter username
    private: no  # it does not prompt the values
  - name: PASSWORD
    prompt: please enter password
    private: yes #it prompt the values

  tasks:
  - name:  printin the values
    ansible.builtin.debug:
      msg: "username: {{USERNAME}} and password: {{PASSWORD}}"    

      