- name: taks level varaibles can override the playlevel variables
  hosts: localhost
  vars:
  - LAND: 100acrs
    CASH: 1000cr

  tasks:
  - name: over ride the paly level varibles
    vars:
    - LAND: 1acrs
      CASH: 1cr
    ansible.builtin.debug:
      msg: "{{LAND}} , {{CASH}}"  # here we are printing over ride values and this only print in this task only , it cant not over ride the next task 
  - name: print varaibles
    ansible.builtin.debug:
      msg: "{{LAND}} , {{CASH}}"


