- name: passing the varibles form console
  hosts: localhost

  tasks:
  - name: print the varibales from command line 
    ansible.builtin.debug:
      msg: "The cours name is {{COURSE}} and trainer name is {{TRAINER}}"  

#  ansible-playbook  -i inventory  -e ansible_user=ec2-user -e ansible_password=DevOps321 08-vars-arg.yaml -e "COURSE=JOINDEVOPS" -e "TRAINER=Shiva"
      