- name: passing the varibles form console
  hosts: localhost

  tasks:
  - name: print the varibales from command line 
    ansible.builtin.debug:
      msg: "The cours name is {{COURSE}} and trainer name is {{TRAINER}}"  