- name: testing varaibles presedence
  hosts: mongodb

  vars:
    NAME: chandu-playlevell
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter name
    private: yes

  tasks:
  - name: task levell varaibles
    #vars:
    #  NAME: chandu-tasklevell
    ansible.builtin.debug:
      msg: "Traner name is {{NAME}}"  


