- name: create user
  hosts: mongodb
  tasks:
  - name: check the roboshop user exit or not
    ansible.builtin.command: null
    rigister: out
    ignore_errors: true
  - name: print the command output
    ansible.builtin.debug:
      msg: 'output is {{out}}'
  - name: print exit status
    ansible.builtin.debug:
      msg: 'output is {{out.rc}}'
  - name: create user
    become: 'yes'
    ansible.builtin.user:
      name: roboshop
    when: out.rc != 0
