- name: practice conditions
  hosts: localhost
  
  vars:
    NAME: "devops"

  tasks:
  - name: printing values  when condition matched
    ansible.builtin.debug:
      msg: "{{NAME}}"
    when: NAME == "devops"    