- name: practice loops
  hosts: localhost

  tasks:
  - name: print the loop values
    ansible.builtin.debug:
      msg: "skills: {{item}}"
    loop:  # this is one type of loops
    - aws
    - jenkins
    - docker
    - k8    