- name: practice second type loops
  hosts: mongodb

  tasks:
  - name: printing the loop values
    ansible.builtin.debug:
      msg: "Hi I am {{item.name}} and age {{item.age}}"

    loop:
    - { name: 'devara', age: 24 }


  - name: install packages
    become: yes
    ansible.builtin.yum:
      name: "{{item}}" 
      state: installed

    loop:
    - nginx
    - postfix
    - mailx
    - cyrus-sasl-plain        
    